import type { InferGetStaticPropsType, NextPage } from 'next'
import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'
import { GetStaticProps } from 'next'
import { Post } from '../types';
import { useState } from 'react';


const API_URL:string = 'https://jsonplaceholder.typicode.com/posts';



const Home: NextPage = ({posts}:InferGetStaticPropsType<typeof getStaticProps>) => {

  const [postList,setPostList] = useState<Post[]>(posts)

  return (
    <div>
      <Head>
        <title>Blog App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {postList.map((post)=>(
          <div key={post.id} className='mb-2'>
            <h3 className='font-medium text-center underline mb-4 uppercase'>{post.title}</h3>
            <p className='text-center'>{post.body}</p>
            <hr/>
          </div>
        ))}
      </main>
      
    </div>
  )
}

export default Home

export const getStaticProps: GetStaticProps = async (context) => {
    const res = await fetch(API_URL);
    const posts:Post[] = await res.json();


    console.log(posts);

    return{
      props: {
        posts,
      },
    }
}
